// Generated by listennotes/devtools/api-sdks/sync.py rust. Do not edit.
use podcast_api::{Client, Response, Result};
use serde_json::Value;

#[rustfmt::skip]
pub async fn call(client: &Client<'_>, operation: &str, params: &Value) -> Result<Response> {
    match operation {
        "search" => client.search(params).await,
        "typeahead" => client.typeahead(params).await,
        "searchEpisodeTitles" => client.search_episode_titles(params).await,
        "spellcheck" => client.spellcheck(params).await,
        "getRelatedSearches" => client.fetch_related_searches(params).await,
        "getTrendingSearches" => client.fetch_trending_searches(params).await,
        "getBestPodcasts" => client.fetch_best_podcasts(params).await,
        "getPodcastById" => client.fetch_podcast_by_id(&scalar(&params["id"]), params).await,
        "deletePodcastById" => client.delete_podcast(&scalar(&params["id"]), params).await,
        "getEpisodeById" => client.fetch_episode_by_id(&scalar(&params["id"]), params).await,
        "getEpisodesInBatch" => client.batch_fetch_episodes(params).await,
        "getPodcastsInBatch" => client.batch_fetch_podcasts(params).await,
        "getCuratedPodcastById" => client.fetch_curated_podcasts_list_by_id(&scalar(&params["id"]), params).await,
        "getGenres" => client.fetch_podcast_genres(params).await,
        "getRegions" => client.fetch_podcast_regions(params).await,
        "getLanguages" => client.fetch_podcast_languages(params).await,
        "justListen" => client.just_listen(params).await,
        "getCuratedPodcasts" => client.fetch_curated_podcasts_lists(params).await,
        "getPodcastRecommendations" => client.fetch_recommendations_for_podcast(&scalar(&params["id"]), params).await,
        "getEpisodeRecommendations" => client.fetch_recommendations_for_episode(&scalar(&params["id"]), params).await,
        "submitPodcast" => client.submit_podcast(params).await,
        "getPlaylistById" => client.fetch_playlist_by_id(&scalar(&params["id"]), params).await,
        "getPlaylists" => client.fetch_my_playlists(params).await,
        "getPodcastAudience" => client.fetch_audience_for_podcast(&scalar(&params["id"]), params).await,
        "getPodcastsByDomainName" => client.fetch_podcasts_by_domain(&scalar(&params["domain_name"]), params).await,
        "createPlaylist" => client.create_playlist(params).await,
        "updatePlaylist" => client.update_playlist(&scalar(&params["id"]), params).await,
        "addPlaylistItem" => client.add_playlist_item(&scalar(&params["id"]), params).await,
        "deletePlaylistItem" => client.delete_playlist_item(&scalar(&params["id"]), &scalar(&params["item_id"]), params).await,
        "updatePlaylistItemNotes" => client.update_playlist_item_notes(&scalar(&params["id"]), &scalar(&params["item_id"]), params).await,
        _ => panic!("unknown operation: {operation}"),
    }
}

#[rustfmt::skip]
pub fn scalar(value: &Value) -> String {
    value.as_str().map(str::to_owned).unwrap_or_else(|| value.to_string())
}
