// Generated by listennotes/devtools/api-sdks/sync.py rust. Do not edit.
use crate::{Client, Response, Result};
use reqwest::Method;
use serde_json::Value;

#[rustfmt::skip]
impl Client<'_> {
    /// Full-text search
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-search).
    pub async fn search(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/search",
            &[], &["q", "sort_by_date", "type", "offset", "len_min", "len_max", "episode_count_min", "episode_count_max", "update_freq_min", "update_freq_max", "genre_ids", "published_before", "published_after", "only_in", "language", "region", "ocid", "ncid", "safe_mode", "unique_podcasts", "interviews_only", "sponsored_only", "page_size"], parameters).await
    }

    /// Typeahead search
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-typeahead).
    pub async fn typeahead(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/typeahead",
            &[], &["q", "show_podcasts", "show_genres", "safe_mode"], parameters).await
    }

    /// Find individual episodes by searching for their titles
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-search_episode_titles).
    pub async fn search_episode_titles(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/search_episode_titles",
            &[], &["q", "podcast_id", "podcast_id_type"], parameters).await
    }

    /// Spell check on a search term
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-spellcheck).
    pub async fn spellcheck(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/spellcheck",
            &[], &["q"], parameters).await
    }

    /// Fetch related search terms
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-related_searches).
    pub async fn fetch_related_searches(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/related_searches",
            &[], &["q"], parameters).await
    }

    /// Fetch trending search terms
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-trending_searches).
    pub async fn fetch_trending_searches(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/trending_searches",
            &[], &[], parameters).await
    }

    /// Fetch a list of best podcasts by genre
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-best_podcasts).
    pub async fn fetch_best_podcasts(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/best_podcasts",
            &[], &["genre_id", "page", "region", "publisher_region", "language", "sort", "safe_mode"], parameters).await
    }

    /// Fetch detailed meta data and episodes for a podcast by id
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-podcasts-id).
    pub async fn fetch_podcast_by_id(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/podcasts/{id}",
            &[("id", id)], &["next_episode_pub_date", "sort"], parameters).await
    }

    /// Request to delete a podcast
    /// See [full API documentation](https://www.listennotes.com/api/docs/#delete-api-v2-podcasts-id).
    pub async fn delete_podcast(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::DELETE, "/podcasts/{id}",
            &[("id", id)], &["reason"], parameters).await
    }

    /// Fetch detailed meta data for an episode by id
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-episodes-id).
    pub async fn fetch_episode_by_id(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/episodes/{id}",
            &[("id", id)], &["show_transcript"], parameters).await
    }

    /// Batch fetch basic meta data for episodes
    /// See [full API documentation](https://www.listennotes.com/api/docs/#post-api-v2-episodes).
    pub async fn batch_fetch_episodes(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::POST, "/episodes",
            &[], &[], parameters).await
    }

    /// Batch fetch basic meta data for podcasts
    /// See [full API documentation](https://www.listennotes.com/api/docs/#post-api-v2-podcasts).
    pub async fn batch_fetch_podcasts(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::POST, "/podcasts",
            &[], &[], parameters).await
    }

    /// Fetch a curated list of podcasts by id
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-curated_podcasts-id).
    pub async fn fetch_curated_podcasts_list_by_id(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/curated_podcasts/{id}",
            &[("id", id)], &[], parameters).await
    }

    /// Fetch a list of podcast genres
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-genres).
    pub async fn fetch_podcast_genres(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/genres",
            &[], &["top_level_only"], parameters).await
    }

    /// Fetch a list of supported countries/regions for best podcasts
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-regions).
    pub async fn fetch_podcast_regions(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/regions",
            &[], &[], parameters).await
    }

    /// Fetch a list of supported languages for podcasts
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-languages).
    pub async fn fetch_podcast_languages(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/languages",
            &[], &[], parameters).await
    }

    /// Fetch a random podcast episode
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-just_listen).
    pub async fn just_listen(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/just_listen",
            &[], &[], parameters).await
    }

    /// Fetch curated lists of podcasts
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-curated_podcasts).
    pub async fn fetch_curated_podcasts_lists(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/curated_podcasts",
            &[], &["page"], parameters).await
    }

    /// Fetch recommendations for a podcast
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-podcasts-id-recommendations).
    pub async fn fetch_recommendations_for_podcast(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/podcasts/{id}/recommendations",
            &[("id", id)], &["safe_mode"], parameters).await
    }

    /// Fetch recommendations for an episode
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-episodes-id-recommendations).
    pub async fn fetch_recommendations_for_episode(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/episodes/{id}/recommendations",
            &[("id", id)], &["safe_mode"], parameters).await
    }

    /// Submit a podcast to Listen Notes database
    /// See [full API documentation](https://www.listennotes.com/api/docs/#post-api-v2-podcasts-submit).
    pub async fn submit_podcast(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::POST, "/podcasts/submit",
            &[], &[], parameters).await
    }

    /// Fetch a playlist's info and items (i.e., episodes or podcasts).
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-playlists-id).
    pub async fn fetch_playlist_by_id(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/playlists/{id}",
            &[("id", id)], &["type", "last_timestamp_ms", "sort"], parameters).await
    }

    /// Fetch a list of your playlists.
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-playlists).
    pub async fn fetch_my_playlists(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/playlists",
            &[], &["sort", "page"], parameters).await
    }

    /// Fetch audience demographics for a podcast
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-podcasts-id-audience).
    pub async fn fetch_audience_for_podcast(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/podcasts/{id}/audience",
            &[("id", id)], &[], parameters).await
    }

    /// Fetch podcasts by a publisher's domain name
    /// See [full API documentation](https://www.listennotes.com/api/docs/#get-api-v2-podcasts-domains-domain_name).
    pub async fn fetch_podcasts_by_domain(&self, domain_name: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::GET, "/podcasts/domains/{domain_name}",
            &[("domain_name", domain_name)], &["page"], parameters).await
    }

    /// Create a playlist.
    /// See [full API documentation](https://www.listennotes.com/api/docs/#post-api-v2-playlists).
    pub async fn create_playlist(&self, parameters: &Value) -> Result<Response> {
        self.request_api(Method::POST, "/playlists",
            &[], &[], parameters).await
    }

    /// Update playlist metadata.
    /// See [full API documentation](https://www.listennotes.com/api/docs/#put-api-v2-playlists-id).
    pub async fn update_playlist(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::PUT, "/playlists/{id}",
            &[("id", id)], &[], parameters).await
    }

    /// Add an episode or podcast to a playlist.
    /// See [full API documentation](https://www.listennotes.com/api/docs/#post-api-v2-playlists-id-items).
    pub async fn add_playlist_item(&self, id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::POST, "/playlists/{id}/items",
            &[("id", id)], &[], parameters).await
    }

    /// Remove an item from a playlist.
    /// See [full API documentation](https://www.listennotes.com/api/docs/#delete-api-v2-playlists-id-items-item_id).
    pub async fn delete_playlist_item(&self, id: &str, item_id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::DELETE, "/playlists/{id}/items/{item_id}",
            &[("id", id), ("item_id", item_id)], &[], parameters).await
    }

    /// Update notes for a playlist item.
    /// See [full API documentation](https://www.listennotes.com/api/docs/#put-api-v2-playlists-id-items-item_id).
    pub async fn update_playlist_item_notes(&self, id: &str, item_id: &str, parameters: &Value) -> Result<Response> {
        self.request_api(Method::PUT, "/playlists/{id}/items/{item_id}",
            &[("id", id), ("item_id", item_id)], &[], parameters).await
    }

}
